In [162]:
import numpy as np
import pandas as pd

In [163]:
colnames = ('Gender, Age, Pre_CanDoCoding, Pre_CodingImportance, Pre_CodingInterest, ITaccess, UseComputersOften, '
            'VisitLibraryBefore, DesireLibraryVisit, Post_CanDoCoding, Post_CodingInterest, Post_CodingImportance, WorkshopFeedback, ' 
            'Scratch_rating, Microbit_rating, MakeArt_rating, MakePong_rating, KanoCode_rating, MakeSnake_rating, HackMinecraft_rating, TerminalQuest_rating, WillVisitLibrary, WillUseDevices').split(', ')
districts = ('pabna, meherpur, kushtia, rajshahi, nawabganj, natore').split(', ')
k = 0
for district in districts:
    df = pd.read_csv('feedback_complete_'+district+'.txt', sep="\t", names=colnames)
    df['Pre_CanDoCoding'].replace({'y':'yes', 'n':'no', 'dk':'dontknow'}, inplace = True)
    df['Post_CanDoCoding'].replace({'y':'yes', 'n':'no', 'dk':'dontknow'}, inplace = True)
    columns = ('Scratch_rating, Microbit_rating, MakeArt_rating, MakePong_rating, KanoCode_rating, MakeSnake_rating, HackMinecraft_rating, TerminalQuest_rating').split(', ')
    for col in columns:
        df[col].replace({66:'not_rated', 99:'not_used'}, inplace = True)
    df.to_csv('WorkshopData/'+district+'.csv')

In [164]:
#colnames = ('gender, age, candocoding, codingimport, codingint, itaccess, usecomp, libraryvisitbefore, libvisitdesire').split(', ')
def convertnumbers(x):
    if x <3:
        x = 'notatall'
    elif x<5:
        x = 'notmuch'
    elif x<7:
        x ='unsure'
    elif x<9:
        x = 'somewhat'
    else:
        x = 'very'
    return x

colnames = ('Gender, Age, Pre_CanDoCoding, Pre_CodingImportance, Pre_CodingInterest, ITaccess, UseComputersOften, '
            'VisitLibraryBefore, DesireLibraryVisit').split(', ')
districts = ('patuakhali, barguna, barishal').split(', ')
for district in districts:
    df = pd.read_csv('feedback_predata_'+district+'.txt', sep="\t ", names=colnames)
    df['Pre_CanDoCoding'].replace({'y':'yes', 'n':'no', 'dk':'dontknow'}, inplace = True)
    df['Pre_CodingImportance'] = df['Pre_CodingImportance'].apply(convertnumbers)
    df['Pre_CodingInterest'] = df['Pre_CodingInterest'].apply(convertnumbers)
    df['DesireLibraryVisit'] = df['DesireLibraryVisit'].apply(convertnumbers)
    df.to_csv('WorkshopData/'+district+'_PreWorkshop.csv')

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [165]:
#colnames = ('candocoding, codingint, codingimport, workshopex, s, mb, ma, mp, kc, ms, hm, tq, libraryvisit, usedevices').split(', ')
colnames = ('Post_CanDoCoding, Post_CodingInterest, Post_CodingImportance, WorkshopFeedback, ' 
            'Scratch_rating, Microbit_rating, MakeArt_rating, MakePong_rating, KanoCode_rating, MakeSnake_rating, HackMinecraft_rating, TerminalQuest_rating, WillVisitLibrary, WillUseDevices').split(', ')
districts = ('patuakhali, barguna, barishal').split(', ')
for district in districts:
    df = pd.read_csv('feedback_postdata_'+district+'.txt', sep="\t", names=colnames)
    df['Post_CanDoCoding'].replace({'y':'yes', 'n':'no', 'dk':'dontknow'}, inplace = True)
    df['Post_CodingImportance'] = df['Post_CodingImportance'].apply(convertnumbers)
    df['Post_CodingInterest'] = df['Post_CodingInterest'].apply(convertnumbers)
    [df[col].replace({66:'not_rated', 99:'not_used'}, inplace = True) for col in columns]
    df.to_csv('WorkshopData/'+district+'_PostWorkshop.csv')
    
df

,Post_CanDoCoding,Post_CodingInterest,Post_CodingImportance,WorkshopFeedback,Scratch_rating,Microbit_rating,MakeArt_rating,MakePong_rating,KanoCode_rating,MakeSnake_rating,HackMinecraft_rating,TerminalQuest_rating,WillVisitLibrary,WillUseDevices
0,yes,very,very,verygood,not_used,5,not_used,not_used,not_used,not_used,not_used,not_used,yes,yes
1,yes,very,very,verygood,5,not_used,5,not_used,4,not_used,not_used,not_used,yes,maybe
2,yes,somewhat,somewhat,good,not_rated,not_used,not_rated,not_used,not_rated,not_used,not_used,not_used,yes,maybe
3,dontknow,very,very,verygood,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,not_rated,yes,maybe
4,yes,very,very,verygood,not_used,not_used,not_used,not_used,not_used,not_rated,not_used,not_used,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,yes,very,somewhat,verygood,5,not_used,5,not_used,not_used,not_used,not_used,not_used,yes,yes
106,yes,very,very,verygood,not_used,5,5,not_used,not_used,5,5,5,yes,yes
107,yes,very,very,verygood,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,not_used,yes,yes
108,yes,very,very,verygood,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,not_used,yes,yes
109,yes,unsure,somewhat,verygood,not_used,not_used,not_used,not_used,not_rated,not_used,not_used,not_rated,yes,yes

In [219]:
def add_workshop(gender, age, priorcoding, s, mb, ma, mp, kc, ms, bk, hm, tq, kanoex, challenge, learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices, location):
    pretqlocs = ['dhaka_1', 'dhaka_2', 'coxsbazar', 'bandarban', 'rangamati', 'dhaka_3', 'jessore', 'khulna', 'narayanganj', 'nilphamari', 'thakurgaon', 'panchagarh']
    if location == 'munshiganj':
        genderR, ageR, priorcodingR, sR, mbR, maR, mpR, kcR, msR, bkR, hmR, learnmoreR, libraryvisitR, usedevicesR = np.loadtxt('feedback_data_munshiganj.txt', unpack=True, dtype = str)
        kanoexR, challengeR, libraryvisitbeforeR,  itaccessR, usecompR, tqR  = [], [], [], [], [], []
        kanoexR, challengeR, libraryvisitbeforeR,  itaccessR, usecompR, tqR  = np.zeros(len(genderR))+5000,np.zeros(len(genderR))+5000, np.zeros(len(genderR))+5000,np.zeros(len(genderR))+5000,np.zeros(len(genderR))+5000, np.zeros(len(genderR))+99
    elif location in pretqlocs:
        genderR, ageR, priorcodingR, sR, mbR, maR, mpR, kcR, msR, bkR, hmR, kanoexR, challengeR, learnmoreR, libraryvisitbeforeR, libraryvisitR,  itaccessR, usecompR, usedevicesR = np.loadtxt('feedback_data_'+location+'.txt', unpack=True, dtype = str)
        tqR = np.zeros(len(genderR))+99
    else:
        genderR, ageR, priorcodingR, sR, mbR, maR, mpR, kcR, msR, bkR, hmR, tqR, kanoexR, challengeR, learnmoreR, libraryvisitbeforeR, libraryvisitR,  itaccessR, usecompR, usedevicesR = np.loadtxt('feedback_data_'+location+'.txt', unpack=True, dtype = str)

    gender = np.concatenate((gender, genderR))
    age = np.concatenate((age, ageR))
    priorcoding = np.concatenate((priorcoding, priorcodingR))
    s = np.concatenate((s, sR))
    mb = np.concatenate((mb, mbR))
    ma = np.concatenate((ma, maR))
    mp = np.concatenate((mp, mpR))
    kc = np.concatenate((kc, kcR))
    ms = np.concatenate((ms, msR))
    bk = np.concatenate((bk, bkR))
    hm = np.concatenate((hm, hmR))
    tq = np.concatenate((tq, tqR))
    learnmore = np.concatenate((learnmore, learnmoreR))
    libraryvisit = np.concatenate((libraryvisit, libraryvisitR))
    usedevices = np.concatenate((usedevices, usedevicesR))
    kanoex = np.concatenate((kanoex, kanoexR))
    challenge = np.concatenate((challenge, challengeR))
    libraryvisitbefore = np.concatenate((libraryvisitbefore, libraryvisitbeforeR))
    itaccess = np.concatenate((itaccess, itaccessR))
    usecomp = np.concatenate((usecomp, usecompR))

        
    return(gender, age, priorcoding, s, mb, ma, mp, kc, ms, bk, hm, tq, kanoex, challenge, 
           learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices)

In [230]:
readgender, readage, priorcoding, reads, readmb, readma, readmp, readkc, readms, readbk, readhm, readtq, kanoex, challenge, learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices = [], [], [], [], [],[], [], [], [], [],[], [], [], [], [],[], [], [], [], []


locations = ['munshiganj', 'dhaka_1', 'dhaka_2', 'coxsbazar', 'bandarban', 'rangamati', 'dhaka_3', 'jessore', 'khulna', 'narayanganj', 'nilphamari', 'thakurgaon', 'panchagarh', 'habiganj', 'sylhet', 'rangpur', 'lalmonirhat', 'dinajpur', 'shatkhira', 'bagerhat', 'mymensingh', 'sherpur', 'jamalpur', 'gazipur', 'tangail', 'manikganj']
#locations =['munshiganj']
k=0
app_columns = ('BuildKano_rating, Scratch_rating, Microbit_rating, MakeArt_rating, MakePong_rating, KanoCode_rating, MakeSnake_rating, HackMinecraft_rating, TerminalQuest_rating').split(', ')
colnames = ('Gender, Age, CodedBefore, Scratch_rating, Microbit_rating, MakeArt_rating, MakePong_rating, KanoCode_rating, MakeSnake_rating, BuildKano_rating, HackMinecraft_rating, TerminalQuest_rating, KanoDeviceFeedback, ChallengingAspect, Want_to_LearnMoreCoding, VisitLibraryBefore, WillVisitLibrary, ITaccess, UseComputersOften, WillUseDevices').split(', ')

for liblocation in locations:
    readgender, readage, priorcoding, reads, readmb, readma, readmp, readkc, readms, readbk, readhm, readtq, kanoex, challenge, learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices = [], [], [], [], [],[], [], [], [], [],[], [], [], [], [],[], [], [], [], []
    gender, age, priorcoding, s, mb, ma, mp, kc, ms, bk, hm, tq, kanoex, challenge, learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices = add_workshop(readgender, readage, priorcoding, reads, readmb, readma, readmp, readkc, readms, readbk, readhm, readtq, kanoex, challenge, learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices, location = liblocation)
    newdf = pd.DataFrame(zip(gender, age, priorcoding, s, mb, ma, mp, kc, ms, bk, hm, tq, kanoex, challenge, learnmore, libraryvisitbefore, libraryvisit,  itaccess, usecomp, usedevices), columns = colnames)
    newdf.replace({'5000':None, '5000.0':None}, inplace = True)
    for app in app_columns:
        newdf[app] = newdf[app].astype(int)
        newdf[app].replace({66:'not_rated', 99:'not_used'}, inplace = True)# for app in app_columns]
    newdf['Age'] = newdf['Age'].astype(int)
    newdf['CodedBefore'] = newdf['CodedBefore'].astype(int)
    newdf['CodedBefore'].replace({1:'Alot', 2:'Alittle', 3:'No', 4:'No'}, inplace = True)
    newdf.to_csv('WorkshopData/'+liblocation+'.csv')

In [235]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   117 non-null    object
 1   Age                      117 non-null    int64
 2   CodedBefore              117 non-null    object
 3   Scratch_rating           117 non-null    object
 4   Microbit_rating          117 non-null    object
 5   MakeArt_rating           117 non-null    object
 6   MakePong_rating          117 non-null    object
 7   KanoCode_rating          117 non-null    object
 8   MakeSnake_rating         117 non-null    object
 9   BuildKano_rating         117 non-null    object
 10  HackMinecraft_rating     117 non-null    object
 11  TerminalQuest_rating     117 non-null    object
 12  KanoDeviceFeedback       117 non-null    object
 13  ChallengingAspect        117 non-null    object
 14  Want_to_LearnMoreCoding  117 non-null    object
 15  VisitLibraryBefore       117 non-null    object
 16  WillVisitLibrary         117 non-null    object
 17  ITaccess                 117 non-null    object
 18  UseComputersOften        117 non-null    object
 19  WillUseDevices           117 non-null    object
dtypes: int64(1), object(19)
memory usage: 18.4+ KB

In [236]:
newdf

,Gender,Age,CodedBefore,Scratch_rating,Microbit_rating,MakeArt_rating,MakePong_rating,KanoCode_rating,MakeSnake_rating,BuildKano_rating,HackMinecraft_rating,TerminalQuest_rating,KanoDeviceFeedback,ChallengingAspect,Want_to_LearnMoreCoding,VisitLibraryBefore,WillVisitLibrary,ITaccess,UseComputersOften,WillUseDevices
0,male,14,Alittle,not_used,not_used,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,good,none,yes,never,yes,school,regularly,maybe
1,male,13,No,not_used,not_used,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,good,none,yes,never,yes,no,veryregularly,maybe
2,male,14,Alittle,not_used,not_used,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,good,experience,yes,never,yes,school,sometimes,yes
3,male,14,Alittle,not_used,not_used,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,good,experience,yes,never,yes,school,sometimes,yes
4,male,15,Alittle,not_rated,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,verygood,english,yes,never,yes,school,regularly,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,female,14,Alittle,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,verygood,experience,yes,regularly,yes,school,sometimes,yes
113,female,15,No,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,verygood,none,yes,never,yes,school,never,yes
114,female,14,No,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,verygood,none,yes,never,yes,school,sometimes,yes
115,female,14,No,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,verygood,none,yes,never,yes,school,sometimes,yes
116,female,12,No,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,not_used,verygood,experience,yes,veryregularly,yes,no,never,yes